### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by laoneo** [Digital-Peak-Incubator/tpl_tauristar#81]
How should we proceed with icons as they are hardcoded at the moment. Would be nice to have them somehow parameterized. Would allow us to introduce new font libraries like font awesome.

**Comment by dneukirchen** [comment]
Hm... hard to say. I agree, that we have to get rid of those hardcoded icon classes at some point. 
Perhaps an IconHelper is needed (something like JHtml::icon($name, $options)).

But i think this is not trivial and we should not touch this at the moment. Its a project on its own. There are so many font libraries out there and most of them have different syntax/api (at least for options like font-awesome´s fa-fw, fa-spin, fa-2x, fa-lg...). 

We have to keep in mind, that svg icons (and other approaches) are getting more and more attention. The browser support for svg-icons is now fairly well and they have some serious advantages over icon fonts. If we touch the way joomla handles icons, i would expect that our new implementation supports inline and external svg icons as well. The problem is, that svg icons have a completely different html markup, than class bases icon fonts. 

We could prefix the icons with a globa ".icon" class, to make it easier to select all icons with css:
Change `<span class="icon-archive"></span>` to `<span class="icon icon-archive"></span>`

If we use sass/less as pre-compilers we could handle the icon-font issue on the template layer with the "extend-feature" of both compilers as a quick solution (Disadvantage: it unnecessarily increases css file size).

**Sass**

```
.icon {
  @extend .fa;
}
.icon-world {
  @extend .fa-world;
}
// Apply fa options
.some-selector > .fa-world {
  @extend .fa-2x;
}
```

**Less**

```
.icon {
  &:extend(.fa);
}
.icon-world {
  &:extend(.fa-world);
}
// Apply fa options
.some-selector > .fa-world {
  &:extend(.fa-2x);
}
```

**Comment by laoneo** [comment]
Closing it as it is a project by it's own.
